name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI/CD  # Specify the environment if using GitHub Environments

    steps:
    - name: Execute remote deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          sudo chmod +x /root/soda-internal-api/update.sh
          echo " Executing CD.sh"
          sudo /root/soda-internal-api/update.sh
          sudo chmod +x /root/asu-soda-newsite/deploy.sh
          ls -l /root/soda-intenal-api
          pwd
          

    
