name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI/CD  # Specify the environment if using GitHub Environments

    steps:
    - name: Execute remote deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          echo $host
          echo $username
          sudo chmod +x /root/soda-internal-api/deploy.sh
          echo " Executing deploy.sh"
          sudo /root/soda-internal-api/deploy.sh
          pwd
          

    
